### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by voidchar** [brandon3055/BrandonsCore#10]
I was playing with the "Project Ozone 2" modpack in which your mods are present and when I died for the third and final time (game over) the game crashed. Do note that I'm new to modded minecraft and don't know a thing about java but the fine folks over at reddit told me that i could post here and i thought "why not, if it helps the mod makers".

cheers 

Here is a part of the crash log that might be relevant to you:

```
---- Minecraft Crash Report ----

// Why is it breaking :(

Time: 2016-09-23 08:56
Description: Exception in server tick loop

java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
at java.util.ArrayList$Itr.next(ArrayList.java:851)
at com.brandon3055.brandonscore.common.handlers.ProcessHandler.onServerTick(ProcessHandler.java:38)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_166_ProcessHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Possibly involved mods --
Details:
Brandon's Core: Version: 1.0.0.12. Main class: com.brandon3055.brandonscore.BrandonsCore. Source: BrandonsCore-1.0.0.12.jar. Url: http://minecraft.curseforge.com/projects/brandons-core.
Brandon's Core: Version: 1.0.0.12. Main class: com.brandon3055.brandonscore.BrandonsCore. Source: BrandonsCore-1.0.0.12.jar. Url: http://minecraft.curseforge.com/projects/brandons-core.
Brandon's Core: Version: 1.0.0.12. Main class: com.brandon3055.brandonscore.BrandonsCore. Source: BrandonsCore-1.0.0.12.jar. Url: http://minecraft.curseforge.com/projects/brandons-core.
Brandon's Core: Version: 1.0.0.12. Main class: com.brandon3055.brandonscore.BrandonsCore. Source: BrandonsCore-1.0.0.12.jar. Url: http://minecraft.curseforge.com/projects/brandons-core.

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 261413032 bytes (249 MB) / 2669150208 bytes (2545 MB) up to 3817865216 bytes (3641 MB)
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 210 mods loaded, 200 mods active

*SNIP*
```

I hope this is of some use to you. Let me know if you need any more info or clarification from me.

**Comment by brandon3055** [comment]
Im not exactly sure how that particular crash cold occur... How/where dud you die?
