### ISSUE TITLE
incompatible classloader

### ISSUE THREAD

**Issue by ldittmar81** [brandon3055/BrandonsCore#12]
Hello,

I got a warning message on startup. Maybe you can fix this... ;-)

`23:28:36] [Client thread/WARN] [FML]: * The API CoFHAPI from source D:\Users\LMD\AppData\Roaming\.minecraft\mods\BrandonsCore-1.10.2-2.1.0.46-universal.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!

[23:28:36] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:113)

[23:28:36] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:173)

[23:28:36] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:231)

[23:28:36] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:521)

[23:28:36] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)

[23:28:36] [Client thread/WARN] [FML]: *  at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)...`

**Comment by brandon3055** [comment]
Yea that is an annoying issue with forge that cant actually be fixed. But its not actually an issue other than the issue of annoying console spam on startup so that message can just be ignored.
