### ISSUE TITLE
Trying to launch Foolcraft server version 1.3.2 and I get this crash ???

### ISSUE THREAD

**Issue by mcdodge34** [brandon3055/BrandonsCore#36]
Ok, out of the .zip file, brand new Foolcraft server, first thing when I start it, I get a crash report, your mod is causing it if I've read correctly so here's the crashlog for you maybe you can solve this issue ???

https://pastebin.com/SPfcCjpW

**Comment by GreatOrator** [comment]
Caused by: java.lang.ExceptionInInitializerError
    at com.teamwizardry.librarianlib.common.util.autoregister.AutoRegisterHandler.handle(AutoRegisterHandler.kt:32)
    at com.teamwizardry.librarianlib.common.core.LibCommonProxy.latePre(LibCommonProxy.kt:51)
    at com.teamwizardry.librarianlib.LateLoader.preInit(LateLoader.kt:13)

Still a bit to learn reading crash logs, that is the guy you need to reach out to, Team Wizardry

**Comment by mcdodge34** [comment]
So who is TeamWizardry exactly, its not clear what mod is the culprit here, but your mod is involved according to lines down there around 270 to 273...

**Comment by GreatOrator** [comment]
Talk to the devs of the pack, but it is not DE.
