### ISSUE TITLE
FakeWorld cannot be cast

### ISSUE THREAD

**Issue by Rinma** [brandon3055/BrandonsCore#39]
I got this error on server start

`BrandonsCore-1.11.2-2.2.0.112-universal.jar`
`CodeChickenLib-1.11.2-3.0.0.274-universal.jar`

```
gameserver_1  | 22:14:35 0|server   | [22:14:35] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.AttachCapabilitiesEvent$Entity@6f530f56:
gameserver_1  | 22:14:35 0|server   | java.lang.ClassCastException: com.brandon3055.brandonscore.lib.FakeWorld cannot be cast to net.minecraft.world.WorldServer
gameserver_1  | 22:14:35 0|server   | 	at noppes.npcs.api.wrapper.EntityWrapper.<init>(EntityWrapper.java:120) ~[EntityWrapper.class:?]
gameserver_1  | 22:14:35 0|server   | 	at noppes.npcs.api.wrapper.EntityLivingBaseWrapper.<init>(EntityLivingBaseWrapper.java:19) ~[EntityLivingBaseWrapper.class:?]
gameserver_1  | 22:14:35 0|server   | 	at noppes.npcs.api.wrapper.EntityLivingWrapper.<init>(EntityLivingWrapper.java:13) ~[EntityLivingWrapper.class:?]
gameserver_1  | 22:14:35 0|server   | 	at noppes.npcs.api.wrapper.AnimalWrapper.<init>(AnimalWrapper.java:10) ~[AnimalWrapper.class:?]
gameserver_1  | 22:14:35 0|server   | 	at noppes.npcs.api.wrapper.WrapperEntityData.getData(WrapperEntityData.java:61) ~[WrapperEntityData.class:?]
gameserver_1  | 22:14:35 0|server   | 	at noppes.npcs.api.wrapper.WrapperEntityData.register(WrapperEntityData.java:52) ~[WrapperEntityData.class:?]
gameserver_1  | 22:14:35 0|server   | 	at noppes.npcs.ServerEventsHandler.attach(ServerEventsHandler.java:217) ~[ServerEventsHandler.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_328_ServerEventsHandler_attach_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:619) ~[ForgeEventFactory.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:589) ~[ForgeEventFactory.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.entity.Entity.<init>(Entity.java:216) ~[sn.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:161) ~[sw.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:91) ~[sx.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.entity.EntityCreature.<init>(SourceFile:21) ~[te.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.entity.EntityAgeable.<init>(EntityAgeable.java:27) ~[sk.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.entity.passive.EntityAnimal.<init>(SourceFile:26) ~[ww.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.entity.passive.EntityPig.<init>(SourceFile:56) ~[xc.class:?]
gameserver_1  | 22:14:35 0|server   | 	at com.brandon3055.draconicevolution.items.MobSoul.lambda$getItemStackDisplayName$0(MobSoul.java:97) ~[MobSoul.class:?]
gameserver_1  | 22:14:35 0|server   | 	at java.util.HashMap.computeIfAbsent(HashMap.java:1126) [?:1.8.0_131]
gameserver_1  | 22:14:35 0|server   | 	at com.brandon3055.draconicevolution.items.MobSoul.func_77653_i(MobSoul.java:94) [MobSoul.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:515) [afj.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:929) [afj.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.stats.StatList.func_75925_c(StatList.java:202) [oa.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.stats.StatList.reinit(StatList.java:348) [oa.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:529) [ForgeModContainer.class:?]
gameserver_1  | 22:14:35 0|server   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
gameserver_1  | 22:14:35 0|server   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
gameserver_1  | 22:14:35 0|server   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
gameserver_1  | 22:14:35 0|server   | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
gameserver_1  | 22:14:35 0|server   | 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
gameserver_1  | 22:14:35 0|server   | 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
gameserver_1  | 22:14:35 0|server   | 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
gameserver_1  | 22:14:35 0|server   | 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
gameserver_1  | 22:14:35 0|server   | 	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) [LoadController.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) [LoadController.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:1083) [Loader.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.revertToFrozen(PersistentRegistryManager.java:492) [PersistentRegistryManager.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:939) [Loader.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:507) [FMLCommonHandler.class:?]
gameserver_1  | 22:14:35 0|server   | 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:544) [MinecraftServer.class:?]
gameserver_1  | 22:14:35 0|server   | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by Rinma** [comment]
With the newest version `Brandon's Core 1.11.2-2.2.1.115-universal` the problem disappears
