### ISSUE TITLE
Null pointer in SF3 on canReceiveEnergy

### ISSUE THREAD

**Issue by odiistorm** [brandon3055/BrandonsCore#44]
Looks like the capacitor is failing on something that is in my inventory.  Believe it started happening when i crafted an enderIO power buffer into my inventory.

Reported exception thrown!
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.world.World.func_72939_s(World.java:1763)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at com.brandon3055.brandonscore.lib.EnergyHelper.canReceiveEnergy(EnergyHelper.java:198)
	at com.brandon3055.draconicevolution.items.tools.DraconiumCapacitor.func_77663_a(DraconiumCapacitor.java:184)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:442)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:959)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:167)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.World.func_72870_g(World.java:1937)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	... 10 more

**Comment by macqo004** [comment]
joining this issue with the same problem

java.lang.NullPointerException: Ticking player
	at com.brandon3055.brandonscore.lib.EnergyHelper.canReceiveEnergy(EnergyHelper.java:198)
	at com.brandon3055.draconicevolution.items.tools.DraconiumCapacitor.func_77663_a(DraconiumCapacitor.java:184)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:442)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by brandon3055** [comment]
Do ether of you have an EIO creative capacitor in your inventory? This is a known issue with that item. Though its possible they now have another item with that issue.

**Comment by odiistorm** [comment]
No I didn't have the creative capacitor in my inventory.  Just the EIO power buffer.

**Comment by covers1624** [comment]
EnderIO's items are broken and have been for a while, they say their item has a capability and then return null for the capability, this is a bug on their end.
