### ISSUE TITLE
crash in Stoneblock 2

### ISSUE THREAD

**Issue by yanderking** [brandon3055/BrandonsCore#80]
So i was playing the modpack stoneblock 2 the other day, made a reactor and let it blew up for fun. Now if i try to read anything about the reactor or the energy network in the draconic evolution tablet my world just crashes with this crash code:
---- Minecraft Crash Report ----
// You're mean.

Time: 2021-05-25 23:48:27 CEST
Description: Registering texture

java.lang.NullPointerException
    at com.brandon3055.brandonscore.lib.ThreadedImageDownloader.loadTexture(ThreadedImageDownloader.java:94)
    at net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:69)
    at com.brandon3055.brandonscore.lib.DLRSCache.getResource(DLRSCache.java:44)
    at com.brandon3055.brandonscore.client.gui.modulargui.markdown.mdelements.ImageElement.layoutElement(ImageElement.java:57)
    at com.brandon3055.brandonscore.client.gui.modulargui.markdown.MDElementContainer.layoutMarkdownElements(MDElementContainer.java:146)
    at com.brandon3055.projectintelligence.client.gui.guielements.GuiPartMDWindow$PageTab.updateMarkdown(GuiPartMDWindow.java:432)
    at com.brandon3055.projectintelligence.client.gui.guielements.GuiPartMDWindow$PageTab.onUpdate(GuiPartMDWindow.java:414)
    at com.brandon3055.brandonscore.client.gui.modulargui.MGuiElementBase.onUpdate(MGuiElementBase.java:785)
    at com.brandon3055.brandonscore.client.gui.modulargui.MGuiElementBase.onUpdate(MGuiElementBase.java:785)
    at com.brandon3055.brandonscore.client.gui.modulargui.GuiElementManager.onUpdate(GuiElementManager.java:321)
    at com.brandon3055.projectintelligence.client.gui.PIGuiContainer.updateScreen(PIGuiContainer.java:293)
    at com.brandon3055.projectintelligence.client.gui.GuiProjectIntelligence.updateScreen(GuiProjectIntelligence.java:243)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1779)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    
    
    i don't know what to do, but it says something with a texture. Please help

**Comment by FoxMcloud5655** [comment]
Closing as stale.
