### ISSUE TITLE
My mod pack crashing

### ISSUE THREAD

**Issue by CuzImZyaDx** [brandon3055/BrandonsCore#85]
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 12/1/21 6:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Brandon's Core (brandonscore)
Caused by: java.lang.NoSuchMethodError: com.brandon3055.draconicevolution.client.creativetab.DETab.<init>(Ljava/lang/String;Ljava/lang/String;I)V
	at net.foxmcloud.draconicadditions.client.creativetab.DATab.<init>(DATab.java:19)
	at net.foxmcloud.draconicadditions.DAFeatures.<clinit>(DAFeatures.java:33)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.brandon3055.brandonscore.registry.ModFeatureParser.parseASMData(ModFeatureParser.java:76)
	at com.brandon3055.brandonscore.BrandonsCore.preInit(BrandonsCore.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 484299528 bytes (461 MB) / 939524096 bytes (896 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_E3 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version          | Source                                             | Signature                                |
	|:----- |:----------------------- |:---------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft               | 1.12.2           | minecraft.jar                                      | None                                     |
	| LCH   | mcp                     | 9.42             | minecraft.jar                                      | None                                     |
	| LCH   | FML                     | 8.0.99.99        | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                   | 14.23.5.2855     | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore           |                  | minecraft.jar                                      | None                                     |
	| LCH   | baubles                 | 1.5.2            | Baubles_1.12_1.5.2.jar                             | None                                     |
	| LCH   | atum                    | 2.0.20           | Atum-1.12.2-2.0.20.jar                             | None                                     |
	| LCH   | codechickenlib          | 3.2.3.357        | CodeChickenLib-1.12.2-3.2.3.357-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux            | 2.1.0            | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCE   | brandonscore            | 2.4.10           | BrandonsCore-1.12.2-2.4.10.198-universal.jar       | None                                     |
	| LC    | draconicevolution       | 2.3.21           | Draconic-Evolution-1.12.2-2.3.21.342-universal.jar | None                                     |
	| LC    | draconicadditions       | 1.17.0           | Draconic-Additions-1.12.2-1.17.0.45-universal.jar  | None                                     |
	| LC    | forgelin                | 1.8.4            | Forgelin-1.8.4.jar                                 | None                                     |
	| LC    | ic2                     | 2.8.170-ex112    | industrialcraft-2-2.8.170-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | galacticraftcore        | 4.0.2.280        | GalacticraftCore-1.12.2-4.0.2.280.jar              | None                                     |
	| LC    | galacticraftplanets     | 4.0.2.280        | Galacticraft-Planets-1.12.2-4.0.2.280.jar          | None                                     |
	| LC    | llibrary                | 1.7.20           | llibrary-1.7.20-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | iceandfire              | 1.9.1            | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
	| LC    | jei                     | 4.16.1.301       | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LC    | mekanism                | 1.12.2-9.8.3.390 | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LC    | teslacorelib            | 1.0.17           | tesla-core-lib-1.12.2-1.0.17.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | industrialforegoing     | 1.12.2-1.12.2    | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| LC    | numina                  | 1.12.2-1.0.38    | Numina-1.12.2-1.0.38.jar                           | None                                     |
	| LC    | powersuits              | 1.12.2-1.0.46    | ModularPowersuits-1.12.2-1.0.46.jar                | None                                     |
	| LC    | nei                     | 2.4.3            | NotEnoughItems-1.12.2-2.4.3.245-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | orespawn                | 1.0.0            | orespawnmc_1.12-development_0.8_-_public.jar       | None                                     |
	| LC    | twilightforest          | 3.11.1021        | twilightforest-1.12.2-3.11.1021-universal.jar      | None                                     |
	| LC    | teslacorelib_registries | 1.0.17           | tesla-core-lib-1.12.2-1.0.17.jar                   | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.148201 Compatibility Profile Context 20.50.02.11 27.20.15002.11002' Renderer: 'AMD Radeon(TM) Graphics'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.148201 Compatibility Profile Context 20.50.02.11 27.20.15002.11002
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by FoxMcloud5655** [comment]
Go update your mods.  They are out of date.

**Comment by CuzImZyaDx** [comment]
this error started when i installed draconic addtions

**Comment by brandon3055** [comment]
Your running BCore 2.4.10 the latest is 2.4.20
https://www.curseforge.com/minecraft/mc-mods/brandons-core/files/3408276
Your running DE 2.3.21 the latest is 2.3.28
https://www.curseforge.com/minecraft/mc-mods/draconic-evolution/files/3431261

**Comment by CuzImZyaDx** [comment]
TNHX BROOOOOOOO
