### ISSUE TITLE
idk why butt brandonscore keeps on crashing with draconic addisions

### ISSUE THREAD

**Issue by kikosun777** [brandon3055/BrandonsCore#89]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 12/14/21 10:41 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Brandon's Core (brandonscore)
Caused by: java.lang.NoSuchMethodError: com.brandon3055.draconicevolution.client.creativetab.DETab.<init>(Ljava/lang/String;Ljava/lang/String;I)V
	at net.foxmcloud.draconicadditions.client.creativetab.DATab.<init>(DATab.java:19)
	at net.foxmcloud.draconicadditions.DAFeatures.<clinit>(DAFeatures.java:33)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.brandon3055.brandonscore.registry.ModFeatureParser.parseASMData(ModFeatureParser.java:76)
	at com.brandon3055.brandonscore.BrandonsCore.preInit(BrandonsCore.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 10897280112 bytes (10392 MB) / 12415139840 bytes (11840 MB) up to 14965276672 bytes (14272 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx14272M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                 | Source                                             | Signature                                |
	|:----- |:-------------------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                  | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LCH   | mcp                        | 9.42                    | minecraft.jar                                      | None                                     |
	| LCH   | FML                        | 8.0.99.99               | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                      | 14.23.5.2855            | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | concheckrmd                | 1.9.5                   | Modpack+Configuration+Checker-1.12.2-v1.9.5.jar    | None                                     |
	| LCH   | damageindicatorsmod        | 1.0                     | [1.12.2]DamageIndicatorsMod-3.5.1.jar              | None                                     |
	| LCH   | aether_legacy              | 1.5.3.2                 | aether-1.12.2-v1.5.3.2.jar                         | None                                     |
	| LCH   | aoa3                       | 3.3.6                   | AoA3-3.3.6.jar                                     | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCH   | appliedenergistics2        | rv6-stable-7            | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | mantle                     | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCH   | thedragonlib               | 1.12.2-5.3.0            | thedragonlib-1.12.2-5.3.0.jar                      | None                                     |
	| LCH   | armorplus                  | 1.12.2-11.28.0.69       | armorplus-1.12.2-11.28.0.69.jar                    | None                                     |
	| LCH   | codechickenlib             | 3.2.2.353               | CodeChickenLib-1.12.2-3.2.2.353-universal (1).jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | avaritia                   | 3.3.0                   | Avaritia-1.12.2-3.3.0.37-universal.jar             | None                                     |
	| LCH   | baubles                    | 1.5.2                   | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | bookshelf                  | 2.3.590                 | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | redstoneflux               | 2.1.0                   | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCE   | brandonscore               | 2.4.20                  | BrandonsCore-1.12.2-2.4.20.162-universal.jar       | None                                     |
	| LC    | draconicevolution          | 2.3.24                  | Draconic-Evolution-1.12.2-2.3.24.349-universal.jar | None                                     |
	| LC    | draconicadditions          | 1.17.0                  | Draconic-Additions-1.12.2-1.17.0.45-universal.jar  | None                                     |
	| LC    | dungeonsmod                | @VERSION@               | DungeonsMod-1.12.2-1.0.8.jar                       | None                                     |
	| LC    | eplus                      | 5.0.176                 | EnchantingPlus-1.12.2-5.0.176.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | umm3185118519              | release 1.5 - MC 1.12.2 | Extended+ItemsOres+[1.12.2]+(release+1.5).jar      | None                                     |
	| LC    | extrautils2                | 1.0                     | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LC    | inventorypets              | 2.0.13                  | inventorypets-1.12-2.0.13.jar                      | None                                     |
	| LC    | jei                        | 4.16.1.301              | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LC    | journeymap                 | 1.12.2-5.7.0            | journeymap-1.12.2-5.7.0.jar                        | None                                     |
	| LC    | manaita_plus               | 1.0.1                   | Manaita+Plus-1.12.2-1.0.1.jar                      | None                                     |
	| LC    | testdummy                  | 1.12                    | MmmMmmMmmMmm-1.12-1.14.jar                         | None                                     |
	| LC    | natura                     | 1.12.2-4.3.2.69         | natura-1.12.2-4.3.2.69.jar                         | None                                     |
	| LC    | prefab                     | 1.3.1.4                 | prefab-1.3.1.4.jar                                 | None                                     |
	| LC    | projecte                   | 1.12.2-PE1.4.1          | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LC    | projectintelligence        | 1.0.9                   | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar  | None                                     |
	| LC    | ruins                      | 17.1                    | Ruins-1.12.2.jar                                   | None                                     |
	| LC    | tlauncher_custom_cape_skin | 1.4                     | tlskincape_1.12.2-1.4.jar                          | None                                     |

	Loaded coremods (and transformers): 
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.10.28 27.20.1028.1' Renderer: 'AMD Radeon(TM) Vega 8 Graphics '
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13596 Compatibility Profile Context 20.10.28 27.20.1028.1
	OpenGlRenderer: AMD Radeon(TM) Vega 8 Graphics 
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by FoxMcloud5655** [comment]
Go update your mods.  You're using old versions.

**Comment by kikosun777** [comment]
> Go update your mods. You're using old versions.

YOOO it worked thank you

**Comment by FoxMcloud5655** [comment]
You're welcome.  Helps to know your own mod :P  Mind closing this issue?
